import type { Implementation, Issue, LLMAgent, LLMAgentConfig, Plan } from '../interfaces/index.js';

/**
 * VoidAgent is a placeholder implementation that logs method calls
 * and returns mock results
 */
export class VoidAgent implements LLMAgent {
    async plan(
        issue: Issue,
        context?: Record<string, unknown>,
        config?: LLMAgentConfig
    ): Promise<Plan> {
        if (!config?.quiet) {
            console.log('[VoidAgent] plan() called');
            console.log('  Issue content length:', issue.content.length);
            console.log('  Context keys:', context ? Object.keys(context) : 'none');
            console.log('  Config:', config ?? 'none');
        }

        return {
            description: 'Mock plan generated by VoidAgent',
            questions: [],
        };
    }

    async implement(
        issue: Issue,
        plan: Plan,
        context?: Record<string, unknown>,
        config?: LLMAgentConfig
    ): Promise<Implementation> {
        if (!config?.quiet) {
            console.log('[VoidAgent] implement() called');
            console.log('  Issue content length:', issue.content.length);
            console.log('  Plan:', plan.description);
            console.log('  Context keys:', context ? Object.keys(context) : 'none');
            console.log('  Config:', config ?? 'none');
        }

        return {
            description: 'Mock implementation completed by VoidAgent',
            success: true,
        };
    }
}
